name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qemuArch:
          - x86_64

    steps:
      # Get the code
      - uses: actions/checkout@v2

      # Publish
      - uses: docker/build-push-action@v1
        with:
          username: nektro
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: nektro/qemu-system
          tags: ${{ matrix.qemuArch }}
          build_args: arch=${{ matrix.qemuArch }}
